#pragma once
#include "Utils/Config/Config.h"
namespace CFG
{
#pragma region Aimbot
	CFGVAR(Aimbot_Enable, false);
	CFGVAR(Aimbot_Key, 0);
	CFGVAR(Aimbot_KeyMode, 0);
	CFGVAR(Aimbot_Melee_KeyMode, 0);
	CFGVAR(Aimbot_Projectile_KeyMode, 0);
	CFGVAR(Aimbot_FOV, 45.f);
	CFGVAR(Aimbot_VisibleCheck, true);
	CFGVAR(Aimbot_TeamCheck, true);
	CFGVAR(Aimbot_SilentAim, false);
	CFGVAR(Aimbot_Aimlock, false); // namespace "CFG" não possui membro "Aimbot_Projectile_KeyMode" Aimbot_Melee_KeyMode
	CFGVAR(Aimbot_Hitscan_Smoothing, 5.f);
	CFGVAR(Aimbot_Hitbox_Head, false);
	CFGVAR(Aimbot_Hitbox_Neck, false);
	CFGVAR(Aimbot_Hitbox_Chest, false);
	CFGVAR(Aimbot_Hitbox_Pelvis, false);
	CFGVAR(Aimbot_Hitbox_Body, false);
	CFGVAR(Aimbot_Hitbox_Buildings, false);
	CFGVAR(Aimbot_Projectile_Enable, false);
	CFGVAR(Aimbot_Projectile_Key, 0);
	CFGVAR(Aimbot_Projectile_FOV, 45.f);
	CFGVAR(Aimbot_Projectile_Smoothing, 5.f);
	CFGVAR(Aimbot_Projectile_TicksPredict, 0);
	CFGVAR(Aimbot_Projectile_TeamCheck, true);
	CFGVAR(Aimbot_Projectile_Mode, 0);
	CFGVAR(Aimbot_ActiveShoot, false);
	CFGVAR(Aimbot_ActiveLagRecords, false);
	CFGVAR(Aimbot_AutoShoot, false);
	CFGVAR(Aimbot_TargetStickies, false);
	CFGVAR(Aimbot_SmoothAutoShoot, false);
	CFGVAR(Aimbot_WaitForHeadshot, false);
	CFGVAR(Aimbot_AutoScope, false);
	CFGVAR(Aimbot_MinigunTapfire, false);
	CFGVAR(Aimbot_WaitForCharge, false)
		CFGVAR(Aimbot_Target_Players, true);
	CFGVAR(Aimbot_Target_Buildings, false);
	CFGVAR(Aimbot_Ignore_Friends, true);
	CFGVAR(Aimbot_Ignore_Invulnerable, true);
	CFGVAR(Aimbot_ActiveMelee, false);
	CFGVAR(Aimbot_Hitscan_Mode, 0);
	CFGVAR(Aimbot_Hitscan_Sort, 0);
	CFGVAR(Aimbot_TargetLagRecords, false);
	CFGVAR(Aimbot_WalkToTarget, false);
	CFGVAR(Aimbot_WhitelistTeammates, false);
	CFGVAR(Aimbot_BaimAfterShots, 0);
	CFGVAR(Aimbot_BaimAfterHealth, 0.18f);
	CFGVAR(Aimbot_Hitbox_Sort, 0);
	CFGVAR(Aimbot_Projectile_NoSpread, false);//Aimbot_Projectile_AimPosition Aimbot_Projectile_BBoxMultipoint Aimbot_Hitscan_AlwaysActive
	CFGVAR(Aimbot_Projectile_AutoDoubleDonk, false);
	CFGVAR(Aimbot_Projectile_AimPosition, 0);
	CFGVAR(Aimbot_Projectile_GroundStrafePrediction, false);
	CFGVAR(Aimbot_Projectile_AdvancedAirStrafe, false);
	CFGVAR(Aimbot_Projectile_RocketSplashPoint, false);
	CFGVAR(Aimbot_Projectile_Sort, 0);
	CFGVAR(Aimbot_Projectile_PredictionMethod, 0);
	CFGVAR(Aimbot_Projectile_MaxSimulationTime, 1.5f);
	CFGVAR(Aimbot_Projectile_MaxTargets, 1);
	CFGVAR(Aimbot_Melee_Active, false);
	CFGVAR(Aimbot_Melee_AlwaysActive, false);
	CFGVAR(Aimbot_Melee_TargetLagRecords, false);
	CFGVAR(Aimbot_Melee_PredictSwing, false);
	CFGVAR(Aimbot_Melee_WalkToTarget, false);
	CFGVAR(Aimbot_Melee_WhipTeammates, false);
	CFGVAR(Aimbot_Melee_Key, 0);
	CFGVAR(Aimbot_Melee_Mode, 0);
	CFGVAR(Aimbot_Melee_Sort, 0);
	CFGVAR(Aimbot_Melee_FOV, 45.f);
	CFGVAR(Aimbot_Melee_Smoothing, 5.f);
	CFGVAR(Aimbot_Melee_PredictSwingTime, 0.18f);
	CFGVAR(Aimbot_Ignore_Invisible, true);
	CFGVAR(Aimbot_Ignore_Taunting, true);
	CFGVAR(Aimbot_Projectile_Active, false);
	CFGVAR(Aimbot_Projectile_Advanced_Head_Aim, false);
	CFGVAR(Aimbot_Projectile_Auto_Double_Donk, false);
	CFGVAR(Aimbot_Projectile_BBox_Multipoint, false);
	CFGVAR(Aimbot_Projectile_Max_Processing_Targets, 5);
	CFGVAR(Aimbot_Projectile_Max_Simulation_Time, 2.0f);
	CFGVAR(Aimbot_Projectile_Rocket_Splash, false);
	CFGVAR(Aimbot_Hitscan_Hitbox, 0);
	CFGVAR(Aimbot_Hitscan_Scan_Head, true);
	CFGVAR(Aimbot_Hitscan_Scan_Body, true);
	CFGVAR(Aimbot_Hitscan_Scan_Arms, false);
	CFGVAR(Aimbot_Hitscan_Scan_Legs, false);
	CFGVAR(Aimbot_Hitscan_Scan_Buildings, true);
#pragma endregion
#pragma region ESP
	CFGVAR(ESP_Enable, false);
	CFGVAR(ESP_Box, false);//ESP_BoxType
	CFGVAR(ESP_BoxType, 0);
	CFGVAR(ESP_Name, false);
	CFGVAR(ESP_Health, false);
	CFGVAR(ESP_Team, false);
	// Novas opções para Skeleton ESP e Chams Box
	CFGVAR(ESP_Skeleton, false);
	CFGVAR(ESP_ChamsBox, false);
	CFGVAR(ESP_ChamsTeam, false);
	CFGVAR(ESP_CaptureFlag, false);
	CFGVAR(ESP_Build, false);
	CFGVAR(ESP_BuildOnlyEnemy, false);
	CFGVAR(ESP_ChamsBuild, false);
	CFGVAR(ESP_ChamsBuildOnlyEnemy, false);
	CFGVAR(ESP_ChamsHideCloaked, false);
	CFGVAR(ESP_ChamsLocalPlayer, false);
	CFGVAR(ESP_ChamsPickups, false); // Adicionado: Chams para pickups
	CFGVAR(ESP_ChamsCaptureFlag, false);
	CFGVAR(ESP_HideCloaked, false);
	CFGVAR(ESP_LocalPlayer, false);
	CFGVAR(ESP_Offscreen, false);
	CFGVAR(ESP_Pickups, false);
	CFGVAR(ESP_PickupsBox, false);
	CFGVAR(ESP_PickupsName, false);
	CFGVAR(Aimbot_DrawFOV, false);
	CFGVAR(ESP_SkeletonBuild, false);
	CFGVAR(ESP_SkeletonBuildOnlyEnemy, false);
	CFGVAR(ESP_SkeletonHideCloaked, false);
	CFGVAR(ESP_SkeletonLocalPlayer, false);
	CFGVAR(ESP_SkeletonPickups, false); // Adicionado: Skeleton para pickups
	CFGVAR(ESP_SkeletonTeam, false);
	CFGVAR(ESP_SkeletonCaptureFlag, false);
	// Bullet Tracer options
	CFGVAR(BulletTracer, false);
	CFGVAR(BulletTracer_Type, 0); // 0=line, 1=line+box, 2=box
	CFGVAR(BulletTracer_Width, 1.0f);
	CFGVAR(BulletTracer_Speed, 0.0f);
	CFGVAR(BulletTracer_Length, 3.0f);
	CFGVAR(ESP_BoxCapture, false);
	CFGVAR(ESP_NameCapture, false);
	CFGVAR(Visuals_Draw_Movement_Path_Style, 0);
	CFGVAR(ESP_HealthType, 0);
	CFGVAR(ESP_Chams_Backtrack, false);
	CFGVAR(ESP_Chams_BacktrackType, 0);
	CFGVAR(ESP_Skeleton_Backtrack, false);
	CFGVAR(ESP_Skeleton_BacktrackType, 0);
	CFGVAR(Logs_Enable, false);
	CFGVAR(Logs_Type, 0);
	CFGVAR(PlayersLogs_Type, 0);
#pragma endregion
#pragma region Misc
	CFGVAR(Misc_AutoJump, true); //Misc_SetupBones_Optimization
	CFGVAR(Misc_SetupBones_Optimization, false);
	CFGVAR(Radio, false)
		CFGVAR(Misc_AutoStrafer_Enable, false);
	CFGVAR(Misc_AutoRocketJump_Enable, false);
	CFGVAR(Misc_AutoRocketJump_Key, 0);
	CFGVAR(Misc_AutoStrafer_Intensity, 45.f);
	CFGVAR(Radio_LocalMusic, false);
	CFGVAR(Radio_Pause, false);
	CFGVAR(Radio_Next, false);
	CFGVAR(Radio_Prev, false);
	CFGVAR(Radio_VolUp, false);
	CFGVAR(Radio_VolDown, false);
	CFGVAR(Misc_AccuracyImprovements, true);
	CFGVAR(Misc_Fake_Taunt, false);
#pragma endregion
#pragma region TEST
	CFGVAR(Important_checkbox, true);
	CFGVAR(TestCombo, 0);
	CFGVAR(TestFloat, 0.f);
	CFGVAR(TestInt, 0);
#pragma endregion
#pragma region Colors
#pragma endregion
	CFGVAR(CurrentSection, 0);
}